inicio/urls.py
from django.urls import path
from inicio import views


app_name= 'inicio'

urlpatterns = [
    path('',views.inicio, name='inicio'),
    path('buscar-mascota/',views.buscar_mascota, name='buscar_mascota'),
    path('cargar-mascota/',views.cargar_mascota, name='cargar_mascota'),
]

proyecto_django/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('', include('inicio.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
    path('ventas/', include('ventas.urls')),
]

inicio/models.py
from django.db import models



class Mascota(models.Model):
    nombre = models.CharField(max_length=20)
    especie = models.CharField(max_length=20)
    raza = models.CharField(max_length=20)
    fecha_nacimiento = models.DateField()
    fecha_registro = models.DateField(auto_now_add=True)

inicio/forms.py
from django import forms
from django.forms import DateInput
from django.utils import timezone



class CreacionMascotaForm(forms.Form):
    nombre = forms.CharField(max_length=20)
    especie = forms.CharField(max_length=20)
    raza = forms.CharField(max_length=20)
    fecha_nacimiento = forms.DateField(
        widget=DateInput(attrs={'type': 'date', 'value': timezone.now().strftime('%Y-%m-%d')}),
    )
    
class BuscarMascota(forms.Form):
    nombre = forms.CharField(max_length=20, required=False)

inicio/views.py
from django.shortcuts import render, redirect
from inicio.forms import CreacionMascotaForm,BuscarMascota
from inicio.models import Mascota


def inicio (request):
    return render (request,'inicio/index.html')

def buscar_mascota (request):
    return render (request,'inicio/buscar_mascota.html')


def cargar_mascota (request):
    if request.method == "POST":
        formulario = CreacionMascotaForm(request.POST)
        
        if formulario.is_valid():
            datos_correctos = formulario.cleaned_data
        
            mascota = Mascota(
                nombre=datos_correctos['nombre'], 
                especie=datos_correctos['especie'],
                raza = datos_correctos['raza'], 
                fecha_nacimiento = datos_correctos['fecha_nacimiento'], 
                )
            mascota.save()

            return redirect('inicio:buscar_mascota')
    
    formulario = CreacionMascotaForm()
    return render(request, 'inicio/cargar_mascota.html', {'formulario': formulario})

def buscar_mascota(request):
    nombre_a_buscar = request.GET.get('nombre', None)
    
    if nombre_a_buscar:
        mascotas = Mascota.objects.filter(nombre__icontains=nombre_a_buscar)
    else:
        mascotas = Mascota.objects.all()
        
    formulario_busqueda = BuscarMascota()
    
    return render(request, 'inicio/buscar_mascota.html', {'mascotas': mascotas, 'formulario': formulario_busqueda})

inicio/templates/inicio/buscar_mascota.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Mascotas</title>
{% endblock title_head %}

{% block h1_header %}

<div style="display: flex; justify-content: center; align-items: center; height: 20vh;">
  <div>
    <h1 style="text-align: center;">Carga a tu mascota:</h1>
    <form action="{% url 'inicio:cargar_mascota' %}" method="POST" style="text-align: center;">
      {% csrf_token %}
      <button style="margin-top: 10px;">Cargar</button>
    </form>
  </div>
</div>

{% endblock h1_header %}


{% block contenido %}


{% if mascotas %}
<style>
    /* Agrega bordes a la tabla */
    table {
      border-collapse: collapse;
      border: 1px solid #000;
      /* Define el ancho máximo de la tabla para centrarla */
      max-width: 800px;
      /* Centra la tabla en la hoja */
      margin-left: auto;
      margin-right: auto;
    }
    
    /* Define el espaciado entre columnas */
    th, td {
      padding: 10px;
    }
    
    /* Alinea el texto a la izquierda en la primera columna */
    th:first-child, td:first-child {
      text-align: left;
    }
    
    /* Centra el texto en las demás columnas */
    th:not(:first-child), td:not(:first-child) {
      text-align: center;
    }
  </style>
  
  <table>
    <thead>
      <form action={% url 'inicio:buscar_mascota' %}>
        {{formulario}}
        </form>
      <tr>
        <th>Registro</th>
        <th>Nombre</th>
        <th>Especie</th>
        <th>Raza</th>
        <th>Fecha de Nacimiento</th>

      </tr>
    </thead>
    <tbody>
      {% for mascota in mascotas %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ mascota.nombre }}</td>
        <td>{{ mascota.especie }}</td>
        <td>{{ mascota.raza }}</td>
        <td>{{ mascota.fecha_nacimiento }}</td>
        <td>{{ mascota.propietario }}</td>
        <td>{{ mascota.contacto_telefonico }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  
  
  

{% else %}
    <h2>No hay datos sobre tu mascota.</h2>
{% endif %}
{% endblock contenido %}

inicio/templates/inicio/cargar_mascota.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Carga Mascota</title>
{% endblock title_head %}
{% load static %}
{% block h1_header %}
<div style="display: flex; justify-content: center; align-items: center; height: 20vh;">
    <div>
      <h1 style="text-align: center;">Carga a tu mascota:</h1>
      <form action="{% url 'inicio:cargar_mascota' %}" method="POST" style="text-align: center;">
        {% csrf_token %}
        <table style="margin: 0 auto;">
          {{formulario}}
        </table>
        <button style="margin-top: 10px;">Crear</button>
      </form>
    </div>
  </div>
{% endblock h1_header %}

{% block contenido %}

{% endblock contenido %}

inicio/templates/inicio/index.html
{% extends 'genericos/base.html' %}
{% load static %}

{% block title_head %}
<title>Veterinaria</title>
{% endblock title_head %}
{% block h1_header %}
<h1>Bienvenidos a Veterinaria "Como perros y gatos"</h1>
{% endblock h1_header %}



{% block contenido %}
<section class="features-icons bg-light text-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
                    <div class="features-icons-icon d-flex justify-content-center align-items-center"><img src={% static 'inicio/assets/dog.ico' %} alt="Icono 1" class="icon-img"></div>
                    <h3>Responsabilidad</h3>
                    <p class="lead mb-0">Recuerda siempre que tu mascota es tu responsabilidad, necesita cuidado, jugar, ser alimentado y mucha atencion!</p>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
                    <div class="features-icons-icon d-flex justify-content-center align-items-center"><img src={% static 'inicio/assets/cat_food.ico' %} alt="Icono 2"class="icon-img"></div>
                    <h3>Alimentacion</h3>
                    <p class="lead mb-0">Tu mascota no puede comer cualquier cosa, necesita una alimentacion balanceada segun su tamaño y edad!</p>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="features-icons-item mx-auto mb-0 mb-lg-3">
                    <div class="features-icons-icon d-flex justify-content-center align-items-center"><img src={% static 'inicio/assets/doctor.ico' %} alt="Icono 3"class="icon-img"></div>
                    <h3>Salud</h3>
                    <p class="lead mb-0">Recuerda que ellos necesitan controles al igual que tu, es importante mantener a su mascota al día con sus vacunas para mantenerla sana y protegida.!</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="showcase">
    <div class="container-fluid p-0">
        <div class="row g-0">
            <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url({% static 'inicio/assets/img/bg-showcase-1.jpg' %})"></div>
            <div class="col-lg-6 order-lg-1 my-auto showcase-text">
                <h2>Nuestro objetivo</h2>
                <p class="lead mb-0">"En nuestra clínica veterinaria, estamos comprometidos con el bienestar integral de su querida mascota, brindándole cuidados médicos y atención compasiva para garantizar que tenga una vida saludable y feliz."</p>
            </div>
        </div>
        <div class="row g-0">
            <div class="col-lg-6 text-white showcase-img" style="background-image: url({% static 'inicio/assets/img/bg-showcase-2.jpg' %})"></div>
            <div class="col-lg-6 my-auto showcase-text">
                <h2>Prevencion</h2>
                <p class="lead mb-0">"En nuestra clínica, creemos en la prevención como parte fundamental del cuidado de los animales, y promovemos la educación a los dueños sobre la importancia de la nutrición adecuada, la vacunación, la esterilización y la prevención de enfermedades para garantizar una vida larga y saludable para sus compañeros peludos."</p>
            </div>
        </div>
        <div class="row g-0">
            <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url({% static 'inicio/assets/img/bg-showcase-3.jpg' %})"></div>
            <div class="col-lg-6 order-lg-1 my-auto showcase-text">
                <h2>Medicina de vanguardia</h2>
                <p class="lead mb-0">"Como profesionales de la salud animal, nos comprometemos a mantenernos actualizados con los avances en la medicina veterinaria y a utilizar equipos de vanguardia y técnicas innovadoras para ofrecer el mejor nivel de atención médica a su mascota, respaldado por nuestro amor y pasión por los animales."</p>
            </div>
        </div>
    </div>

{% endblock contenido %}