inicio/urls.py
from django.urls import path
from inicio import views


app_name= 'inicio'

urlpatterns = [
    path('',views.inicio, name='inicio'),
    path('buscar-mascota/',views.buscar_mascota, name='buscar_mascota'),
    path('cargar-mascota/',views.cargar_mascota, name='cargar_mascota'),
]

proyecto_django/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('', include('inicio.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
    path('ventas/', include('ventas.urls')),
]

usuarios/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from usuarios import views

app_name= 'usuarios'

urlpatterns = [
    path('logout/',LogoutView.as_view(template_name='usuarios/logout.html'),name='logout'),
    path('login/', views.login, name='login'),
    path('registro/', views.registro, name='registro'),
    path('perfil/editar/', views.editar_perfil, name='editar_perfil'),
    path('perfil/editar/cambiar_contrasenia', views.CambiarContrasenia.as_view(), name='cambiar_contrasenia'),
]

ventas/urls.py
from django.urls import path
from ventas import views


app_name= 'ventas'

urlpatterns = [
    path('',views.index, name='index'),
    path('animales/',views.AnimalListView.as_view(), name='lista_animales'),
    path('animales/crear',views.AnimalListView.as_view(), name='lista_animales'),    
    path('animales/<int:pk>/modificar',views.AnimalUpdateView.as_view(), name='modificar_animales'),
    path('animales/<int:pk>/eliminar',views.AnimalUpdateView.as_view(), name='eliminar_animales'),
    path('categorias/',views.CategoriaListView.as_view(), name='lista_categorias'),
    path('categorias/crear',views.CategoriaListView.as_view(), name='lista_categorias'),    
    path('categorias/<int:pk>/modificar',views.CategoriaUpdateView.as_view(), name='modificar_categorias'),
    path('categorias/<int:pk>/eliminar',views.CategoriaUpdateView.as_view(), name='eliminar_categorias'),
    path('tipos/',views.TipoListView.as_view(), name='lista_tipos'),
    path('tipos/crear',views.TipoListView.as_view(), name='lista_tipos'),    
    path('tipos/<int:pk>/modificar',views.TipoUpdateView.as_view(), name='modificar_tipos'),
    path('tipos/<int:pk>/eliminar',views.TipoUpdateView.as_view(), name='eliminar_tipos'),
    path('productos/',views.ProductoListView.as_view(), name='lista_productos'),
    path('productos/crear',views.ProductoListView.as_view(), name='lista_productos'),    
    path('productos/<int:pk>',views.ProductoDetailView.as_view(), name='detalle_productos'),    
    path('productos/<int:pk>/modificar',views.ProductoUpdateView.as_view(), name='modificar_productos'),
    path('productos/<int:pk>/eliminar',views.ProductoUpdateView.as_view(), name='eliminar_productos'),
    path('comentarios/',views.ComentarioListView.as_view(), name='lista_comentarios'),
    path('comentarios/crear',views.ComentarioListView.as_view(), name='lista_comentarios'),    
    path('comentarios/<int:pk>',views.ComentarioDetailView.as_view(), name='detalle_comentarios'),    
    path('comentarios/<int:pk>/modificar',views.ComentarioUpdateView.as_view(), name='modificar_comentarios'),
    path('comentarios/<int:pk>/eliminar',views.ComentarioUpdateView.as_view(), name='eliminar_comentarios'),
]

templates/genericos/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title_head %}
        <title>template base</title>
        {% endblock title_head %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href={% static 'inicio/assets/favicon.ico' %} />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'inicio/css/styles.css' %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href={% url 'inicio:inicio' %}>Inicio</a>
                <a class="navbar-brand" href={% url 'inicio:buscar_mascota' %}>Mascotas</a>
                {% if request.user.is_authenticated %}
                <a class="navbar-brand" href={% url 'ventas:index' %}>Tienda</a>
                <div class="d-flex">
                    <a class="navbar-brand mr-auto" href="#">{{ request.user.username }}</a>
                    <a class="btn btn-primary" href="{% url 'usuarios:logout' %}">logout</a>
                </div>
                {% else %}
                <div class="d-flex flex-column">
                    <a class="btn btn-primary btn-sm mb-2" href="{% url 'usuarios:registro' %}">Registrarse</a>
                    <a class="btn btn-primary btn-sm" href="{% url 'usuarios:login' %}">Login</a>
                </div>
                {% endif %}

            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            {% block h1_header %}
                            <h1 class="mb-5">h1 base</h1>
                            {% endblock h1_header %}
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% block contenido %}
        {% endblock contenido %}
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">   
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                            <li class="list-inline-item">⋅</li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                    </div>
                </div>
            </div>
        </footer>
    </body>
</html>

templates/genericos/base2.html
<!DOCTYPE html>
<html lang="es">
  {% load static %}
<head>
  <meta charset="UTF-8">

  <title>
    {% block Title %}
    Tienda en línea  
    {% endblock Title %}
  </title>

  <meta name="description" content="Bienvenido a nuestra tienda en línea">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/x-icon" href={% static 'inicio/assets/favicon.ico' %} />
  <!-- Bootstrap icons-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
  <!-- Google fonts-->
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
  <!-- Core theme CSS (includes Bootstrap)-->
  <link href={% static 'inicio/css/styles.css' %} rel="stylesheet" />
  <style>
    body {
      background-color: #f6e9e6;
      font-family: Arial, sans-serif;
      margin: 0;
      text-align: center;
    }
    header {
      background-color: #c7ded9;
      padding: 20px;
      text-align: center;
    }
    h1 {
      margin: 0;
      font-size: 36px;
      font-weight: bold;
      color: #555;
      text-align: center;
    }
    nav {
      background-color: #f6e9e6;
      padding: 10px;
      text-align: center;
    }
    nav ul {
      list-style: none;
      margin: 0;
      padding: 0;
      display: flex;
    }
    nav li {
      margin-right: 10px;
    }
    nav a {
      display: block;
      padding: 5px 10px;
      text-decoration: none;
      color: #555;
    }
    nav a:hover {
      background-color: #c7ded9;
      color: #fff;
    }
    main {
      padding: 20px;
    }
    .product {
      background-color: #fff;
      border-radius: 5px;
      box-shadow: 0 0 5px rgba(0,0,0,0.3);
      padding: 20px;
      margin-bottom: 20px;
    }
    .product h2 {
      margin: 0;
      font-size: 24px;
      color: #555;
    }
    .product img {
      max-width: 100%;
      margin-bottom: 10px;
    }
    .product p {
      margin: 0;
      color: #777;
    }
    footer {
      background-color: #c7ded9;
      color: #fff;
      padding: 20px;
      text-align: center;
    }
  </style>
</head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
          <div class="container">
              <a class="navbar-brand" href={% url 'inicio:inicio' %}>Inicio</a>
              <a class="navbar-brand" href={% url 'inicio:buscar_mascota' %}>Mascotas</a>
              {% if request.user.is_authenticated %}
              <a class="navbar-brand" href={% url 'ventas:index' %}>Tienda</a>
              <div class="d-flex">
                  <a class="navbar-brand mr-auto" href="#">Bienvenido: {{ request.user.username }}</a>
                  <a class="btn btn-primary" href="{% url 'usuarios:logout' %}">logout</a>
              </div>
              <a href="#" class="cart">
                <i class="fas fa-shopping-cart"></i>
                Ver carrito
              </a>
              {% else %}
              <div class="d-flex flex-column">
                  <a class="btn btn-primary btn-sm mb-2" href="{% url 'usuarios:registro' %}">Registrarse</a>
                  <a class="btn btn-primary btn-sm" href="{% url 'usuarios:login' %}">Login</a>
              </div>
              {% endif %}

          </div>
      </nav>
<body>
  <header>
    {% block header %}
    <h1>Tienda en línea</h1>
    {% endblock header %}
  </header>

  <nav>
    {% block bodynav %}
    <ul>
      <li><a href="#">Inicio</a></li>
      <li><a href="#">Categoría 1</a></li>
      <li><a href="#">Categoría 2</a></li>
      <li><a href="#">Categoría 3</a></li>
      <li><a href="#">Categoría 4</a></li>
    </ul>
    {% endblock bodynav %}
  </nav>

<main>
{% block main %}
{% endblock main %}
</main>
<footer>
  <p>© 2023 Tienda en línea. Todos los derechos reservados.</p>
</footer>
<!-- Agrega aquí tus scripts al final de la página, antes del cierre del body -->
</body>
</html>