inicio/urls.py
from django.urls import path
from inicio import views


app_name= 'inicio'

urlpatterns = [
    path('',views.inicio, name='inicio'),
    path('buscar-mascota/',views.buscar_mascota, name='buscar_mascota'),
    path('cargar-mascota/',views.cargar_mascota, name='cargar_mascota'),
]

proyecto_django/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('', include('inicio.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
    path('ventas/', include('ventas.urls')),
]

usuarios/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from usuarios import views

app_name= 'usuarios'

urlpatterns = [
    path('logout/',LogoutView.as_view(template_name='usuarios/logout.html'),name='logout'),
    path('login/', views.login, name='login'),
    path('registro/', views.registro, name='registro'),
    path('perfil/editar/', views.editar_perfil, name='editar_perfil'),
    path('perfil/editar/cambiar_contrasenia', views.CambiarContrasenia.as_view(), name='cambiar_contrasenia'),
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User

class InfoExtra(models.Model):
    avatar = models.ImageField(upload_to='avatares', null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    fecha_registro = models.DateField(auto_now_add=True)
    

usuarios/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django import forms


class FormularioRegistro(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField()
    password2 = forms.CharField()
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {k: '' for k in fields}
        
        
class EdicionPerfil(UserChangeForm):
    password = None
    email = forms.EmailField()
    instagram = forms.URLField()
    telefono= forms.IntegerField()
    direccion= forms.CharField(max_length =20)
    first_name = forms.CharField(label='Nombre', max_length=30)
    last_name = forms.CharField(label='Apellido', max_length=30)
    
    avatar = forms.ImageField(required=False)
    
    class Meta:
        model = User
        fields = ['email','instagram','telefono','direccion','first_name', 'last_name', 'avatar']

usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login as login_django
from usuarios.forms import FormularioRegistro, EdicionPerfil
from django.contrib.auth.decorators import login_required
from usuarios.models import InfoExtra
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin


def login(request):
    
    if request.method == 'POST':
        formulario = AuthenticationForm(request, data=request.POST)
        
        if formulario.is_valid():
            usuario = formulario.cleaned_data.get('username')
            contrasenia = formulario.cleaned_data.get('password')
            
            user = authenticate(username=usuario, password=contrasenia)
            
            login_django(request, user)
            
            InfoExtra.objects.get_or_create(user=user)
            
            return redirect('inicio:inicio')
        else:
            return render(request, 'usuarios/login.html', {'form': formulario})
    
    formulario = AuthenticationForm()
    return render(request, 'usuarios/login.html', {'form': formulario})

def registro(request):
    
    if request.method == 'POST':
        formulario = FormularioRegistro(request.POST)
        
        if formulario.is_valid():
            formulario.save()
            
            return redirect('usuarios:login')
        else:
            return render(request, 'usuarios/registro.html', {'form': formulario})
    
    formulario = FormularioRegistro()
    return render(request, 'usuarios/registro.html', {'form': formulario})
    
@login_required
def editar_perfil(request):
    
    if request.method == 'POST':
        formulario = EdicionPerfil(request.POST, request.FILES, instance=request.user)
        
        if formulario.is_valid():
            
            if formulario.cleaned_data.get('avatar'):
                request.user.infoextra.avatar = formulario.cleaned_data.get('avatar')
                request.user.infoextra.save()
            
            formulario.save()
            
            return redirect('usuarios:editar_perfil')
        else:
            return render(request, 'usuarios/editar_perfil.html', {'form': formulario})
    
    formulario = EdicionPerfil(initial={'avatar': request.user.infoextra.avatar}, instance=request.user)
    return render(request, 'usuarios/editar_perfil.html', {'form': formulario})

class CambiarContrasenia(LoginRequiredMixin, PasswordChangeView):
    template_name = 'usuarios/cambiar_contrasenia.html'
    success_url = reverse_lazy('usuarios:editar_perfil')

usuarios/templates/usuarios/cambiar_contrasenia.html
{% extends 'genericos/base.html' %}
{% load static %}

{% block title_head %}
<title>Cambiar Contrasenia</title>
{% endblock title_head %}
{% block h1_header %}
<h1>Cambiar Contrasenia</h1>
{% if form.error %}
<p>Formulario invalido</p>
{% endif %}
<form action={% url 'usuarios:cambiar_contrasenia' %} method="post">
    {% csrf_token %}
    {{form}}
    <button>Cambiar</button>
    </form>
{% endblock h1_header %}



{% block contenido %}

{% endblock contenido %}

usuarios/templates/usuarios/editar_perfil.html
{% extends 'genericos/base.html' %}
{% load static %}

{% block title_head %}
<title>Editar perfil</title>
{% endblock title_head %}
{% block h1_header %}
<h1>Editar perfil</h1>

{% if form.error %}
<p>Formulario invalido</p>
{% endif %}

<form action={% url 'usuarios:editar_perfil' %} method="post" enctype='multipart/form-data'>
    {% csrf_token %}
    {{form}}
    <button type='button'><a href={% url 'usuarios:cambiar_contrasenia' %}>Cambiar Contrasenia</a></button>
    <button>Editar</button>
    </form>

{% endblock h1_header %}



{% block contenido %}

{% endblock contenido %}

usuarios/templates/usuarios/login.html
{% extends 'genericos/base.html' %}
{% load static %}

{% block title_head %}
<title>Login</title>
{% endblock title_head %}
{% block h1_header %}
<h1>Login</h1>
{% if form.error %}
<p>Datos Erroneos</p>
{% endif %}
<form action={% url 'usuarios:login' %} method="post">
    {% csrf_token %}
    {{form}}
    <button>Logearse</button>
    </form>
{% endblock h1_header %}



{% block contenido %}

{% endblock contenido %}

usuarios/templates/usuarios/logout.html
{% extends 'genericos/base.html' %}
{% load static %}

{% block title_head %}
<title>Logout</title>
{% endblock title_head %}
{% block h1_header %}
<h1>Te deslogeaste con exito!!</h1>
{% endblock h1_header %}



{% block contenido %}

{% endblock contenido %}

usuarios/templates/usuarios/registro.html
{% extends 'genericos/base.html' %}
{% load static %}

{% block title_head %}
<title>Registro</title>
{% endblock title_head %}
{% block h1_header %}
<div style="display: flex; justify-content: center; align-items: center; height: 20vh;">
    <div>
      <h1 style="text-align: center;">Registrarse:</h1>

{% if form.error %}
<p>Los datos no son correctos</p>
{% endif %}


      <form action="{% url 'usuarios:registro' %}" method="POST" enctype='multipart/form-data' style="text-align: center;">
        {% csrf_token %}
        <table style="margin: 0 auto;">
          {{form}}
        </table>
        <button style="margin-top: 10px;">Registrarse</button>
      </form>
    </div>
  </div>
{% endblock h1_header %}



{% block contenido %}

{% endblock contenido %}